config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :orders
  resources :carts
  resources :products
  get 'inventario', to: 'products#stocks'
  get 'carritos-abandonados', to: 'carts#losts'
  delete 'logout', to: 'users#sign_out'
  get 'ordenes', to: 'orders#orders'
  resources :statuses
  #delete 'remove-cart/:id_product/:id_cart', to: 'in_shopping_carts#remove-cart'
  resources :suppliers
  resources :brands
  resources :in_shopping_carts, only: [:create, :destroy]
  root 'products#index'
  post 'create-order/:id_cart/:user', to: 'orders#newOrder', as: 'nueva_factura'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get '/login', to: 'users#login'

  post '/sign_in', to: 'users#sign_in'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :products
  has_many :in_shopping_carts

  enum status: [:incomplete, :complete]

  def status_cart
    Order.where(cart_id: id).blank? ? "<span class='label label-danger'>Abandonado</span>" : "<span class='label label-success'>Completado</span>"
  end

  def total
    total = 0
    self.in_shopping_carts.each do |cr|
      total += cr.product ? cr.product.price / 100 : 0
    end
    return "$#{total} MXN"
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @cart = Cart.find(cookies[:cart_id])
    @cart_session = @cart
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @cart.destroy
    redirect_to root_path
  end
  def losts
    @cart_session = Cart.find(cookies[:cart_id])
    @carts = Cart.all
  end
  private

    def set_cart
      @cart = Cart.find(params[:id])
    end


    def cart_params
      params.require(:cart).permit(:products_id, :status)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :products_id %>
    <%= f.text_field :products_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<section class="container">
  <h1>Tu carrito de compras</h1>
  <% if @cart.in_shopping_carts.length == 0 %>
    <div class="alert alert-warning" role="alert">
      <strong>¡Ey!</strong> No tienes ningún producto en tu carrito de compras, visita nuestro catálogo de <%= link_to 'productos', products_path%>.
    </div>
  <%else%>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Foto</th>
          <th>Producto</th>
          <th>Descripción</th>
          <th>Precio</th>
          <th class="text-right" colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @cart.in_shopping_carts.each do |in_s| %>
          <% product = in_s.product %>
          <tr>
            <td><%= image_tag product.photo.url(:thumb), width: '40', height: '40'%></td>
            <td class="text-center"><%= product.name %></td>
            <td><%= product.description%></td>
            <td class="text-center"><%= product.to_price %></td>
            <td><%#= link_to 'Ver producto', product %> <%= link_to 'Eliminar', in_shopping_cart_path(in_s), method: :delete%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <div class="actions">
    <% current_user = @current_user ? @current_user['id'] : 1 %>
    <% if @user_signed_in%>
      <% if @cart.in_shopping_carts.length > 0%>
        <%= link_to "Comprar ahora", nueva_factura_path(@cart.id, current_user), method: :post, class: 'btn btn-lg btn-success' %>
      <% end %>
    <% else %>
      <div class="alert alert-danger" role="alert">
        <strong>¡Ey!</strong> Para terminar tu orden, necesitas iniciar sesión.
        <p>Puedes <%= link_to 'crear una cuenta', new_user_path %> o <%= link_to 'iniciar sesión', login_path%></p>
      </div>
    <% end %>
  </div>
  <br>
  
</section>

app/views/carts/losts.html.erb
<div class="container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th class="text-center">Número de productos</th>
				<th class="text-center">Total</th>
				<th class="text-center">Estado</th>
				<th class="text-center">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<%@carts.each do |cart|%>
				<tr>
					<th><%= cart.id %></th>
					<td class="text-center"><%= cart.in_shopping_carts.length %></td>
					<td class="text-center"><%= cart.total%></td>
					<td class="text-center"><%= cart.status_cart.html_safe %></td>
					<td class="text-center"><%= link_to "Eliminar", cart, method: :delete%></td>
				</tr>
			<%end%>
		</tbody>
	</table>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Products:</strong>
  <%= @cart.products %>
</p>

<p>
  <strong>Status:</strong>
  <%= @cart.status %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>