config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :orders
  resources :carts
  resources :products
  get 'inventario', to: 'products#stocks'
  get 'carritos-abandonados', to: 'carts#losts'
  delete 'logout', to: 'users#sign_out'
  get 'ordenes', to: 'orders#orders'
  resources :statuses
  #delete 'remove-cart/:id_product/:id_cart', to: 'in_shopping_carts#remove-cart'
  resources :suppliers
  resources :brands
  resources :in_shopping_carts, only: [:create, :destroy]
  root 'products#index'
  post 'create-order/:id_cart/:user', to: 'orders#newOrder', as: 'nueva_factura'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get '/login', to: 'users#login'

  post '/sign_in', to: 'users#sign_in'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :product
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  
  
  def index
    @brands = Brand.all
  end

  
  
  def show
    @brands = Brand.all
  end

  
  def new
    @brand = Brand.new
  end

  
  def edit
  end

  
  
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Se creó correctmente la marca.' }
      else
        format.html { render :new }
      end
    end
  end

  
  
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Se actualizado la marca.' }
      else
        format.html { render :edit }
      end
    end
  end

  
  
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'La marca se eliminó correctmente.' }
    end
  end

  private
    
    def set_brand
      @brand = Brand.find(params[:id])
    end


    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(brand) do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre de la marca' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field actions">
    <%= f.submit 'Guardar', class: 'btn btn-lg btn-success' %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<div class="container">
	<h1>Nueva marca</h1>

	<%= render 'form', brand: @brand %>

	<%= link_to 'Back', brands_path %>
	
</div>

app/views/brands/show.html.erb
<div class="container">
	<h1><strong><%= @brand.name%></strong> <small>(<%= @brand.product.length%>)</small></h1>
	<div class="col-xs-12 col-md-9">
		<%= render 'products/show', products: @brand.product%>
	</div>
	<%= render 'partials/brands', brands: @brands%>
</div>