config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :orders
  resources :carts
  resources :products
  get 'inventario', to: 'products#stocks'
  get 'carritos-abandonados', to: 'carts#losts'
  delete 'logout', to: 'users#sign_out'
  get 'ordenes', to: 'orders#orders'
  resources :statuses
  #delete 'remove-cart/:id_product/:id_cart', to: 'in_shopping_carts#remove-cart'
  resources :suppliers
  resources :brands
  resources :in_shopping_carts, only: [:create, :destroy]
  root 'products#index'
  post 'create-order/:id_cart/:user', to: 'orders#newOrder', as: 'nueva_factura'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get '/login', to: 'users#login'

  post '/sign_in', to: 'users#sign_in'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :product
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :products
  has_many :in_shopping_carts

  enum status: [:incomplete, :complete]

  def status_cart
    Order.where(cart_id: id).blank? ? "<span class='label label-danger'>Abandonado</span>" : "<span class='label label-success'>Completado</span>"
  end

  def total
    total = 0
    self.in_shopping_carts.each do |cr|
      total += cr.product ? cr.product.price / 100 : 0
    end
    return "$#{total} MXN"
  end
end

app/models/in_shopping_cart.rb
class InShoppingCart < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
  has_many :statuses


  def status
    if !self.statuses.blank?
      self.statuses.last.status_label.html_safe
    else
      "<label class='label label-warning'>Sin actualizar</label>".html_safe
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :brand
  has_many :inshoppingcarts
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :wholesale_price, presence: true

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def to_price
    return "$#{ price / 100}"
  end
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :order

  enum status: [:payment_pending, :payment_received, :sent, :delivered ]

  def status_label
    if self.payment_pending?
      "<label class='label label-warning'>Pago pendiente</label>"
    elsif self.payment_received?
      "<label class='label label-info'>Pago recibido</label>"
    elsif self.sent?
      "<label class='label label-primary'>Enviado</label>"
    elsif self.delivered?
        "<label class='label label-success'>Entregado</label>"
    else
      "<label class='label label-warning'>Sin actualizar</label>"
    end
  end

  def last
    self.inspect

  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  enum profile: [:client, :admin]

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  
  
  def index
    @brands = Brand.all
  end

  
  
  def show
    @brands = Brand.all
  end

  
  def new
    @brand = Brand.new
  end

  
  def edit
  end

  
  
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Se creó correctmente la marca.' }
      else
        format.html { render :new }
      end
    end
  end

  
  
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Se actualizado la marca.' }
      else
        format.html { render :edit }
      end
    end
  end

  
  
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'La marca se eliminó correctmente.' }
    end
  end

  private
    
    def set_brand
      @brand = Brand.find(params[:id])
    end


    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @cart = Cart.find(cookies[:cart_id])
    @cart_session = @cart
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @cart.destroy
    redirect_to root_path
  end
  def losts
    @cart_session = Cart.find(cookies[:cart_id])
    @carts = Cart.all
  end
  private

    def set_cart
      @cart = Cart.find(params[:id])
    end


    def cart_params
      params.require(:cart).permit(:products_id, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def login

  end

  def sign_out
    session[:current_user_id] = nil
    redirect_to root_path, notice: 'Se cerró sesión correctamente.'
  end
  def sign_in
    user = User.where('email = ?', params[:email]).first
    if user != nil
      if user.password == params[:password]
        if params[:password] == user.password_confirmation
          session[:current_user_id] = user.id
          redirect_to root_path
        end
      end
    end
  end


  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aigle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="before_header col-xs-12">
      <div class="container">
        <div class="col-xs-12 col-md-6 text-left">
          <% if @user_signed_in %>
            <p>¡Hola <%= @current_user.first_name %>, bienvenido(a)! <%= link_to 'Cerrar sesión', logout_path, method: :delete%></p>
          <%else %>
            <%= link_to 'Iniciar sesión', login_path  %>
          <% end %>
        </div>
        <div class="col-xs-12 col-md-6 text-right">
          <%= link_to "Tienes (#{@cart_session.in_shopping_carts.length}) producto(s) en tu carrito", carts_path %>
        </div>
        
      </div>
    </div>
    <header>
      <div class="container">
        <%= image_tag('logo_blanco.png', class: 'img-responsive logo')%>       
      </div>
    </header>
    
    <% if  @user_signed_in && @current_user.admin? %>
      <%= render 'partials/menu_admin' %>
    <% end %> 
    <% if  @user_signed_in && @current_user.client? %>
      <%= render 'partials/menu_client' %>
    <% end %>
    <br>
    <section class="main">
      <div class="container">
        <header class="main__header"></header>
        <div class="row main__description"></div>
      </div>
    </section> 
    <br>
    <div class="container" style="display:<%= notice.blank? && alert.blank? ? 'none' : 'block'%>;">
      <div class="alert alert-info" role="alert">
        <strong><%= notice %></strong>
        <strong><%= alert %></strong>
      </div>
    </div>
    <br>
    <%= yield %>
    <div class="container">
      <%= image_tag "4.svg", class: "img-responsive" %>
    </div>
    <br>
    <br>
    <br>
  </body>
</html>

app/views/partials/_brands.html.erb
<div class="col-xs-12 col-md-2">
  <div class="panel panel-default">
    <div class="panel-heading">Marcas</div>
    <table class="table">
      <tbody>
        <% brands.each do |provider|%>
          <tr>
            <td><%= link_to provider.name, provider%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= image_tag "2.svg", class: "img-responsive" %>
</div>

app/views/partials/_menu_admin.html.erb
<div class="menu">
  	<div class="container">
		<ul>
			<li><%= link_to 'Inicio', root_path%></li>
			<li><%= link_to('Agregar productos', new_product_path) %></li>
			<li><%= link_to 'Agregar proveedor', new_supplier_path %></li>
			<li><%= link_to 'Agregar marca', new_brand_path %></li>
			<li><%= link_to 'Inventario',inventario_path %></li>
			<li><%= link_to 'Carritos abandonados', carritos_abandonados_path %></li>
			<li><%= link_to 'Ordenes', ordenes_path %></li>
		</ul>
  	</div>
</div>

app/views/partials/_menu_client.html.erb
<div class="menu">
  	<div class="container">
		<ul>
			<li><%= link_to 'Inicio', root_path%></li>
			<li><%= link_to('Productos', products_path) %></li>
			<li><%= link_to('Mis ordenes', orders_path) %></li>


		</ul>
  	</div>
</div>